sed -i 's/json.NewEncoder(w).Encode(v)/_ = json.NewEncoder(w).Encode(v)/g' internal/server/server.go
sed -i 's/s.store.Close()/_ = s.store.Close()/g' internal/server/server.go
sed -i 's/json.Unmarshal(prevData, &prev)/_ = json.Unmarshal(prevData, \&prev)/g' internal/observe/observe.go
sed -i 's/os.WriteFile(statePath(), data, 0600)/_ = os.WriteFile(statePath(), data, 0600)/g' internal/observe/observe.go
sed -i 's/os.MkdirAll(dir, 0755)/_ = os.MkdirAll(dir, 0755)/g' internal/observe/observe.go
sed -i 's/json.Unmarshal(data, &st)/_ = json.Unmarshal(data, \&st)/g' internal/observe/observe.go
sed -i 's/\<rows.Close()\>/_ = rows.Close()/g' internal/db/sqlite.go
sed -i 's/\<fkRows.Close()\>/_ = fkRows.Close()/g' internal/db/sqlite.go
sed -i 's/\<colIdxRows.Close()\>/_ = colIdxRows.Close()/g' internal/db/sqlite.go
sed -i 's/\<idxRows.Close()\>/_ = idxRows.Close()/g' internal/db/sqlite.go
sed -i 's/\<colRows.Close()\>/_ = colRows.Close()/g' internal/db/sqlite.go
sed -i 's/\<conn.Close()\>/_ = conn.Close()/g' internal/db/sqlite.go
sed -i 's/\<rows.Close()\>/_ = rows.Close()/g' internal/db/postgres.go
sed -i 's/\<fkRows.Close()\>/_ = fkRows.Close()/g' internal/db/postgres.go
sed -i 's/\<idxRows.Close()\>/_ = idxRows.Close()/g' internal/db/postgres.go
sed -i 's/\<conn.Close()\>/_ = conn.Close()/g' internal/db/postgres.go
sed -i 's/\<rows.Close()\>/_ = rows.Close()/g' internal/db/mysql.go
sed -i 's/\<fkRows.Close()\>/_ = fkRows.Close()/g' internal/db/mysql.go
sed -i 's/\<idxRows.Close()\>/_ = idxRows.Close()/g' internal/db/mysql.go
sed -i 's/\<conn.Close()\>/_ = conn.Close()/g' internal/db/mysql.go
sed -i 's/\<active.Close()\>/_ = active.Close()/g' internal/db/db.go
sed -i 's/\<row.Close()\>/_ = row.Close()/g' internal/analyze/cardinality.go
sed -i 's/\<conn.Close()\>/_ = conn.Close()/g' cmd/use.go
sed -i 's/\<store.Close()\>/_ = store.Close()/g' cmd/server.go
sed -i 's/fmt.Scanln(&resp)/_, _ = fmt.Scanln(\&resp)/g' cmd/query.go
sed -i 's/\<rows.Close()\>/_ = rows.Close()/g' cmd/pg_helper.go
sed -i 's/rows.Scan(&buf)/_ = rows.Scan(\&buf)/g' cmd/pg_helper.go
sed -i 's/os.Setenv(parts\[0\], parts\[1\])/_ = os.Setenv(parts[0], parts[1])/g' cmd/onboard.go
sed -i 's/\<conn.Close()\>/_ = conn.Close()/g' cmd/init.go
sed -i 's/os.Setenv("AI_PROVIDER", cfg.AIProvider)/_ = os.Setenv("AI_PROVIDER", cfg.AIProvider)/g' cmd/init.go
sed -i 's/\<rows.Close()\>/_ = rows.Close()/g' cmd/index.go
sed -i 's/fmt.Scanln(&response)/_, _ = fmt.Scanln(\&response)/g' cmd/index.go
sed -i 's/\<testConn.Close()\>/_ = testConn.Close()/g' cmd/doctor.go
sed -i 's/fmt.Sscanf(choice, "%d", &idx)/_, _ = fmt.Sscanf(choice, "%d", \&idx)/g' cmd/connect.go
sed -i 's/\<rows.Close()\>/_ = rows.Close()/g' cmd/check.go
