package cmd

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/DynamicKarabo/basemake/internal/analyze"
	"github.com/DynamicKarabo/basemake/internal/db"
	"github.com/DynamicKarabo/basemake/internal/license"
	"github.com/spf13/cobra"
)

var indexCmd = &cobra.Command{
	Use:   "index",
	Short: "Manage index recommendations",
	Long: `View, apply, and dismiss index recommendations generated by 'basemake analyze'.

Recommendations are persisted in ~/.basemake/recommendations.json and include
performance estimates, trade-offs, and partial index suggestions.

  basemake index list               # Show all pending recommendations
  basemake index list --all         # Show all (including applied/dismissed)
  basemake index list --stale       # Show recommendations > 7 days old
  basemake index apply <id>         # Apply a recommendation (with confirmation)
  basemake index dismiss <id>       # Dismiss a recommendation`,
}

var indexListCmd = &cobra.Command{
	Use:   "list",
	Short: "List index recommendations",
	Args:  cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		store, err := analyze.LoadRecs()
		if err != nil {
			return fmt.Errorf("load recommendations: %w", err)
		}

		showAll, _ := cmd.Flags().GetBool("all")
		showStale, _ := cmd.Flags().GetInt("stale")

		var recs []analyze.Recommendation
		if showStale > 0 {
			recs = store.StaleReport(showStale)
			fmt.Fprintf(os.Stderr, "Recommendations older than %d days:\n\n", showStale)
		} else if showAll {
			recs = store.Recommendations
		} else {
			recs = store.Pending()
		}

		if len(recs) == 0 {
			fmt.Println("No recommendations to show.")
			fmt.Println("Run 'basemake analyze <query>' to generate index suggestions.")
			return nil
		}

		for _, rec := range recs {
			sug := rec.Suggestion
			age := time.Since(rec.CreatedAt).Truncate(time.Hour)
			statusIcon := "🟡"
			switch rec.Status {
			case "applied":
				statusIcon = "✅"
			case "dismissed":
				statusIcon = "⛔"
			}

			fmt.Printf("%s %s\n", statusIcon, rec.ID)
			fmt.Printf("    SQL:  %s\n", sug.CreateSQL)
			fmt.Printf("    📊    %s\n", sug.EstImprovement)
			fmt.Printf("    Status: %s | Created: %s ago\n", rec.Status, age)
			for _, tr := range sug.Tradeoffs {
				fmt.Printf("    ⚠  %s\n", tr)
			}
			fmt.Println()
		}

		// Show stale summary if not already showing stale
		if showStale == 0 {
			stale := store.StaleReport(7)
			if len(stale) > 0 {
				fmt.Fprintf(os.Stderr, "⏰ %d recommendation(s) are > 7 days old. Run 'basemake index list --stale' to review.\n", len(stale))
			}
		}

		return nil
	},
}

var indexApplyCmd = &cobra.Command{
	Use:   "apply <id>",
	Short: "Apply an index recommendation (with confirmation)",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		if !requireLicense(license.FeatureIndexApply) {
			os.Exit(1)
			return nil
		}
		id := args[0]

		store, err := analyze.LoadRecs()
		if err != nil {
			return fmt.Errorf("load recommendations: %w", err)
		}

		// Find the recommendation
		var rec *analyze.Recommendation
		for i := range store.Recommendations {
			if store.Recommendations[i].ID == id {
				rec = &store.Recommendations[i]
				break
			}
		}
		if rec == nil {
			return fmt.Errorf("recommendation %q not found — run 'basemake index list' to see available IDs", id)
		}
		if rec.Status == "applied" {
			return fmt.Errorf("recommendation %q was already applied on %s", id, rec.UpdatedAt.Format(time.RFC822))
		}
		if rec.Status == "dismissed" {
			return fmt.Errorf("recommendation %q was dismissed on %s", id, rec.UpdatedAt.Format(time.RFC822))
		}

		// Show the SQL and ask for confirmation
		fmt.Println("Index to create:")
		fmt.Println()
		fmt.Printf("  %s\n\n", rec.Suggestion.CreateSQL)
		fmt.Println("Trade-offs:")
		for _, tr := range rec.Suggestion.Tradeoffs {
			fmt.Printf("  ⚠ %s\n", tr)
		}
		fmt.Println()
		fmt.Print("Apply this index? This creates a real index on your database. [y/N]: ")

		var response string
		_, _ = fmt.Scanln(&response)
		response = strings.TrimSpace(strings.ToLower(response))
		if response != "y" && response != "yes" {
			fmt.Println("Cancelled.")
			return nil
		}

		// Connect to database and apply
		conn, err := db.ActiveConnection()
		if err != nil {
			return fmt.Errorf("no active connection — run 'basemake connect' first: %w", err)
		}
		defer conn.Close()

		fmt.Fprintf(os.Stderr, "Creating index...\n")
		rows, err := conn.Query(cmd.Context(), rec.Suggestion.CreateSQL)
		if err != nil {
			return fmt.Errorf("create index failed: %w", err)
		}
		for rows.Next() {
			// Drain results (CREATE INDEX returns nothing in PG but may in MySQL)
		}
		rows.Close()

		// Update status
		if err := store.Apply(id); err != nil {
			return fmt.Errorf("update status: %w", err)
		}

		fmt.Println("✅ Index created successfully!")
		fmt.Printf("  %s\n", rec.Suggestion.CreateSQL)
		return nil
	},
}

var indexDismissCmd = &cobra.Command{
	Use:   "dismiss <id>",
	Short: "Dismiss an index recommendation",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id := args[0]
		store, err := analyze.LoadRecs()
		if err != nil {
			return fmt.Errorf("load recommendations: %w", err)
		}
		if err := store.Dismiss(id); err != nil {
			return err
		}
		fmt.Printf("⛔ Dismissed recommendation %q\n", id)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(indexCmd)
	indexCmd.AddCommand(indexListCmd)
	indexCmd.AddCommand(indexApplyCmd)
	indexCmd.AddCommand(indexDismissCmd)

	indexListCmd.Flags().Bool("all", false, "Show all recommendations (including applied/dismissed)")
	indexListCmd.Flags().Int("stale", 0, "Show recommendations older than N days (e.g. --stale 7)")
}
